// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmQ-NKlZ7ticvJnOQbqwOMB7jRdCalfic',
    appId: '1:629360165632:web:6d45a04a7211630866a9e5',
    messagingSenderId: '629360165632',
    projectId: 'fluttter-auth-83789',
    authDomain: 'fluttter-auth-83789.firebaseapp.com',
    storageBucket: 'fluttter-auth-83789.appspot.com',
    measurementId: 'G-N9H0DVBFGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD51Cy9MYBbYqyPf6CxfdQbMztWxqsEX4s',
    appId: '1:629360165632:android:402a74ecb786b21d66a9e5',
    messagingSenderId: '629360165632',
    projectId: 'fluttter-auth-83789',
    storageBucket: 'fluttter-auth-83789.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-189EJWkrtbtWyk5GQChoB7MdRVKQL5U',
    appId: '1:629360165632:ios:add1b4b6c864517366a9e5',
    messagingSenderId: '629360165632',
    projectId: 'fluttter-auth-83789',
    storageBucket: 'fluttter-auth-83789.appspot.com',
    androidClientId: '629360165632-f9gcm8a9033jrvqr8g3k3q0gm3ov6uc3.apps.googleusercontent.com',
    iosClientId: '629360165632-091hf7jrpf98t9oluhvlpq27be5r35n1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-189EJWkrtbtWyk5GQChoB7MdRVKQL5U',
    appId: '1:629360165632:ios:cb08ace8644cce0366a9e5',
    messagingSenderId: '629360165632',
    projectId: 'fluttter-auth-83789',
    storageBucket: 'fluttter-auth-83789.appspot.com',
    androidClientId: '629360165632-f9gcm8a9033jrvqr8g3k3q0gm3ov6uc3.apps.googleusercontent.com',
    iosClientId: '629360165632-36ff44511d3f6otnmpqm795l56rufcpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebase.RunnerTests',
  );
}
